apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-web-app
    app.kubernetes.io/instance: go-web-app
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
        - image: adeways2000/go-web-app:12585210378
          name: go-web-app
          ports:
            - containerPort: 8080