apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-web-app
    app.kubernetes.io/instance: go-web-app
  name: go-web-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: go-web-app
  type: NodePort
